# SwiftLint configuration file
disabled_rules:
  - trailing_whitespace
  - line_length

opt_in_rules:
  - empty_count
  - missing_docs
  - force_unwrapping

included:
  - Sources
  - Tests

excluded:
  - Pods
  - Carthage
  - fastlane

line_length:
  warning: 120
  error: 200

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100
