name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: install trunk
        run: |
          curl -LO https://trunk.io/releases/trunk
          chmod +x trunk

      - name: lint
        run: ./trunk check --all --ci
